on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-10.15}
          - {os: macos-11}

    steps:
      - uses: r-lib/actions/setup-r@v1

      - name: test gmp
        shell: bash
        run: |
          R -e "install.packages('gmp', repos = 'https://mac.r-project.org')"
          R -e "S <- gmp::Stirling2(50,10)"
